# Generated by Django 3.1 on 2025-04-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(blank=True, choices=[('customer', 'customer'), ('vendor', 'vendor')], max_length=20, null=True),
        ),
    ]
