# Generated by Django 3.1 on 2025-04-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(blank=True, choices=[('Customer', 'Customer'), ('Vendor', 'Vendor')], max_length=20, null=True),
        ),
    ]
